---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stellmar/repositories/stellmarfarm
    - /bin/cp -R images $DEPLOYPATH
     - /bin/cp -R recipes $DEPLOYPATH
      - /bin/cp -R components $DEPLOYPATH